COMPILER=g++

lsys.dll: lsys.o
	@echo Creating lsys.dll using OpenGL
	$(COMPILER) -static -shared lsys.o -lopengl32 -lglu32 -o lsys.dll

lsys.o: lsys.i
	@echo Compiling lsys.i
	$(COMPILER) -std=c++11 -c lsys.i -o lsys.o
